# Generated by Django 2.2.28 on 2025-02-14 13:23

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('rango_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
